[build]
builder = "nixpacks"

[deploy]
startCommand = "cd myproject && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[env]
NIXPACKS_PYTHON_VERSION = "3.11"
