# Generated by Django 5.1.7 on 2025-04-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="is_inactive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="apikey",
            name="last_regenerated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
